service: flask-api-serverless

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./

functions:
  app:
    image:
      name: appimage
    timeout: 20
    events:
      - http: 'ANY /similar'
      - http: 'ANY /result'